import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import './styles/custom-tailwind.css'; /* Import custom utilities */
import Head from 'next/head';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <>
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body
        className={'antialiased'}
      >
        {children}
      </body>
    </>
    </html>
  );
}
