import type { Metadata } from "next";
import "./globals.css";
import './styles/custom-tailwind.css'; /* Import custom utilities */
import Head from 'next/head';
import { Inter } from 'next/font/google';


// Import multiple font weights here
const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // Add only the weights you want
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="inter.variable">
      <body
        className={'font-sans'}
      >
        {children}
      </body>
    </html>
  );
}
